name: Build & Deploy Spring app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy spring app
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/test-ci-cd:$(date'%Y%m%d%H%M%S')
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to docker hub
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/test-ci-cd:$(date'%Y%m%d%H%M%S')